# Calculus

-   Calculus is about dealing with infinitesimal values.
-   We are going to focus on two big ideas:
    -   Derivatives
    -   Integrals

## Derviatives

-   "Derivative" is just a fancy term for slope.
-   Slope is the rate of change $\frac{\delta y}{\delta x}$ or $\frac{d y}{d x}$.
-   Specifically, the derivative is the *instantaneous* rate of change.
-   We need slope for our statistics, which are all about fitting lines.
-   We also need slope for taking maxima and minima.
-   The equation for a line is $y = mx + b$. What is its slope?

### Calculating derivatives

-   Slope is rise over run, which is $\dfrac{f(x+\Delta x)-f(x)}{\Delta x}$
-   To see why, consider the slope of a line connecting two points: $$m = \displaystyle\frac{f(x_2) - f(x_1)}{x_2-x_1}$$
-   We can define $x_2 = x_1 + \Delta x$ (or equivalently $\Delta x = x_2 - x_1$) $$m = \dfrac{f(x_1+ \Delta x) - f(x_1)}{\Delta x}$$

------------------------------------------------------------------------

-   As we've seen, for a curve, we need to be infinitely close for our line's defining points, yielding $$\lim_{\Delta x\to 0} \frac{f(x+ \Delta x)-f(x)}{\Delta x}$$
-   This gives us this instantaneous slope (rate of change) of a function at every point on its domain. The above equation is the definition of the derivative.

### Notation

-   $\frac{d}{dx} f(x)$ is read "The derivative of $f$ of $x$ with respect to $x$." - You can also say "The instantaneous rate of change in $f$ of $x$ with respect to $x$."

-   If $y=f(x)$, $\frac{dy}{dx}$ is "The derivative of $y$ with respect to $x$".

::: callout-warning
Do not try to cancel out the $d$'s, no matter how tempting it is.
:::

-   There is the advantage of always specifying the variable with respect to which we're differentiating (it's the one in the denominator).

-   Lagrange's prime notation: $f'(x)$ (read: "$f$ prime $x$") is the derivative of $f(x)$.

------------------------------------------------------------------------

**Examples**

-   What is $\dfrac{d(x^2)}{dx}$?

    -   $x^2$
    -   $2 x^{2-1}$ -$2x$

-   What is $\frac{d(4x^3)}{dx}$?

    -   $4x^3$

    -   $4*3 x^{3-1}$

    -   $12x^2$

------------------------------------------------------------------------

**Practice**

Take the derivative of each of these. $$x^3$$ $$3x^2$$ $$60x^{11}$$ $$x$$ $$\frac{4}{x^2} $$ $$9 \sqrt{x}$$ $$6 x^{5/2}$$ $$11,596,232$$

------------------------------------------------------------------------

**Practice**

Evaluate the derivatives at $x=2$ and $x=-1$ $$x^3$$ $$3x^2$$ $$60x^{11}$$ $$x$$ $$\frac{4}{x^2} $$ $$9 \sqrt{x}$$ $$6 x^{5/2}$$ $$11,596,232$$

------------------------------------------------------------------------

**Practice**

Take the derivative of each of these. $$x^3$$ $$3x^2$$ $$60x^{11}$$ $$x$$ $$\frac{4}{x^2} $$ $$9 \sqrt{x}$$ $$6 x^{5/2}$$ $$11,596,232$$

------------------------------------------------------------------------

Evaluate the derivatives at $x=2$ and $x=-1$ $$x^3$$ $$3x^2$$ $$60x^{11}$$ $$x$$ $$\frac{4}{x^2} $$ $$9 \sqrt{x}$$ $$6 x^{5/2}$$ $$11,596,232$$

------------------------------------------------------------------------

### Special functions

A few functions have particular rules:

-   $\frac{d (ln(x))}{dx}=\frac{1}{x}$

-   $\dfrac{d (log_b(x))}{dx}=\dfrac{1}{x*ln(b)}$

-   $\frac{d (e^x)}{dx}=e^x$

-   $\frac{d (a^x)}{dx}=a^x ln(a)$

-   $\frac{dy}{dx}c=0$

-   $\frac{d (x^x)}{dx}=x^x (1+ln(x))$

### Derivatives with addition and substraction

-   This is perhaps the rasiest rule to remember: $$\frac{d (f(x) \pm g(x))}{dx}=f'(x) \pm g'(x)$$

------------------------------------------------------------------------

**Practice**

Take the derivative of each of these: $$x^2 + x +5$$ $$x^4 - 4x^3 + 5x^2 + 8x - 6$$ $$3x^5 - 6x^2$$ $$5x^2 + 8 \sqrt{x} - \frac{1}{x}$$ $$ln(x) + 5e^x - 4x^3$$

## Advanced rules

### Product rule

-   This rule is more complicated: $$\frac{d (f(x) \times g(x))}{dx}=f'(x)g(x) + g'(x)f(x)$$
-   Example: $2x \times 3x$

------------------------------------------------------------------------

**Practice**

Take the derivative of each of these: $$x^3 * x$$ $$e^x * x^2$$ $$ln(x) * x^{-3}$$

::: {.callout-tip title="Reminder"}
$$\frac{d (f(x) * g(x))}{dx}=f'(x)g(x) + g'(x)f(x)$$
:::

### Quotient rule

$$\frac{d \frac{f(x)}{g(x)}}{dx}=\frac{f'(x)g(x) - g'(x)f(x)}{[g(x)]^2}$$ If you're having trouble with this, just apply the product rule to: $$\frac{d[f(x)*g^{-1}(x)]}{dx}$$

::: {.callout-tip title="Reminder"}
$$\frac{d \frac{f(x)}{g(x)}}{dx}=\frac{f'(x)g(x) - g'(x)f(x)}{[g(x)]^2}$$
:::

### Chain rule

$$\frac{d [f(g(x))]}{dx}=f'(g(x)) * g'(x)$$

Let's take the derivative of a function of a function: $$\frac{d[ln(x^2)]}{dx}$$ $$f(x)=ln(x)$$ $$g(x)=x^2$$ $$f'(x)=\frac{1}{x}$$ $$g'(x)=2x$$ $$ \frac{1}{x^2}*2x = \frac{2}{x}$$

------------------------------------------------------------------------

**Practice**

Take the derivative of each of these: $$ (3x^4-8)^2 $$ $$e^{x^2}$$

::: {.callout-tip title="Reminder"}
$$\frac{d (f(g(x))}{dx}=f'(g(x)) * g'(x)$$
:::

### Second derivative

-   Same process as taking single derivative, except input for second derivative is output from first.
-   Second derivative tells us whether the slope of a function is increasing, decreasing, or staying the same at any point $x$ on the function's domain.
-   Example: driving a car.
    -   $f(x)$ = distance traveled at time $x$
    -   $f'(x)$ = speed at time $x$
    -   $f''(x)$ = acceleration at time $x$

------------------------------------------------------------------------

Graph $f(x) = x^2$, $f'(x)$, and $f''(x)$.

------------------------------------------------------------------------

$$\frac{d^2(x^4)}{dx^2}=f''(x^4)$$

-   First, we take the first derivative: $$f'(x^4)=4x^3$$
-   Then we use that output to take the second derivative: $$f''(x^4)=f'(4x^3)=12x^2$$

**Practice**

Take the second derivative of the following functions: $$x^5$$ $$6x^2$$ $$4 ln(x)$$ $$3x$$ $$4x^{3/2}$$

## Differentiable and Continuous Functions

-   Informally: A function is continuous at a point if its graph has no holes or breaks at that point

-   Formally: A function is continuous at a point $a$ if: $$\displaystyle\lim_{x \to a} f(x)=f(a)$$

------------------------------------------------------------------------

Continuity requires 3 conditions to hold:

-   $f(a)$ is defined ($a$ is in the domain of $f$)

-   $\displaystyle\lim_{x \to a} f(x)$ exists

-   $\displaystyle\lim_{x \to a} f(x) = f(a)$ (the value of $f$ equals the limit of $f$ at $a$)

------------------------------------------------------------------------

Differentiable:

-   If $f'(x)$ exists, $f$ is differentiable at $x$.

-   If $f$ is differentiable at every point of an open interval $I$, $f$ is differentiable on $I$.

-   Graph must have a (non-vertical) tangent line at each point, be relatively smooth, and not contain any breaks, bends, or cusps.

------------------------------------------------------------------------

-   If a function is differentiable at a point, it is also continuous at that point.
-   If a function is continuous at a point, it is *not* necessarily differentiable at that point.

### When is f not differentiable?

When does $f'(x)$ not exist?

-   When the function is discontinuous at that point.
    -   Jump or break in the graph.
-   There are different slopes approaching the point from the left and from the right.
    -   Corner point
-   When the graph of the function has a vertical tangent line at that point.
    -   Cusp
    -   Vertical inflection point

## Extrema and optimization

*Optimization* lets us find the minimum or maximum value a function takes.

-   Formal theory
    -   Utility maximization, continuous choices
-   Ordinary Least Squares (OLS)
    -   Focuses on *minimizing* the squared errors between observed data and values predicted by a regression
-   Maximum Likelihood Estimation (MLE)
    -   Focuses on *maximizing* a likelihood function, given observed values

### Extrema

Informally, a maximum is just the highest value a function takes, and a minimum is the lowest value.

-   Easy to identify extrema (maxima or minima) intuitively by looking at a graph of the function.
    -   Maxima are high points ("peaks")
    -   Minima are low points ("valleys")
-   Extrema can be *local* or *global*.

### Identifying extrema

-   The derivative of a function gives the rate of change.

-   When the derivative is zero (or fails to exist), the function has *usually* reached a (local) maximum or minimum.

-   At a maximum, the function must be increasing before the point and decreasing after it.

-   At a minimum, the function must be decreasing before the point and increasing after it.

-   We'll start by identifying points where this is the case ("critical points" or "stationary points").

::: callout-note
A point where $f'(x)=0$ or $f'(x)$ does not exist is called a *critical point* (or *stationary point*). Local extrema occur at critical points, but not all critical points are extrema. For instance, sometimes the graph is changing between concave and convex ("inflection points"). Sometimes the function is not differentiable at that point for other reasons.
:::

------------------------------------------------------------------------

So we can find the local maxima and/or minima of a function by taking the derivative, setting it equal to zero, and solving for x (or whatever).

$$f'(x)=0$$

This gives us the first-order condition (FOC).

### Minimum or maximum?

**BUT** we don't know if we've found a maximum or minimum, or even if we've found an extremum or just an inflection point.

### Second derivatives

The second derivative gives us the rate of change of the rate of change of the original function. So it tells us whether the slope is getting larger or smaller.

$$f(x) = x^2$$ $$f'(x) = 2x$$ $$f''(x) = 2$$

------------------------------------------------------------------------

Second Derivative Test - Start by identifying $f''(x)$

-   Substitute in the stationary points $(x^*)$ identified from the FOC

-   $f''(x^*) > 0$ we have a local minimum

-   $f''(x^*) < 0$ we have a local maximum

-   $f''(x^*) = 0$ we (may) have an inflection point - need to calculate higher-order derivatives (don't worry about this now)

Collectively these give use the Second-Order Condition (SOC).

### Local vs. Global Extrema

To find the minimum/maximum on some interval, compare the local min/max to the value of the function at the interval's endpoints.

-   To find the global minimum/maximum, check the function's limits as it approaches $+ \infty$ and $- \infty$.

-   Extreme value theorem: if a real-valued function $f$ is continuous on the closed interval \[a,b\], then $f$ must attain a (global) maximum and a (global) minimum.

## Partial derivatives

-   Can take derivative with respect to different variables

-   Notation: For a function $fy=(x,z)=xz$, we might want to know how the function changes with $x$:

$$ \displaystyle\frac{\partial}{\partial_x}f(x,y) = \frac{\partial_y}{\partial_x} = \partial_x f$$

-   Treat all other variables as constants and take derivative with respect to the variable of interest (here $x$).

------------------------------------------------------------------------

How do we take a partial derivative?

Treat all other variables as *constants* and take *derivative* with respect to the variable of interest.

From our earlier example: $$y = f(x,z) = xz $$ $$ \displaystyle\frac{\partial_y}{\partial_x} = ?$$

------------------------------------------------------------------------

$$y = f(x,z) = xz $$ $$ \displaystyle\frac{\partial_y}{\partial_x} = z$$

Why? Because the partial derivative of $xz$ with respect to $x$ treats $z$ as a constant.

What is $\displaystyle\frac{\partial_y}{\partial_z}?$

### Application

-   $\frac{\partial (x^2y+xy^2-x)}{\partial x}$

-   We apply the addition rule to take the derivative of each term with respect to x.

-   $\frac{\partial (x^2y)}{\partial x}$+$\frac{\partial (xy^2)}{\partial x}$+$\frac{\partial (-x)}{\partial x}$

-   $2xy+y^2-1$

------------------------------------------------------------------------

-   $\frac{\partial (x^2y+xy^2-x)}{\partial y}$

-   We apply the addition rule to take the derivative of each term with respect to y

-   $\frac{\partial (x^2y)}{\partial y}$+$\frac{\partial (xy^2)}{\partial y}$+$\frac{\partial (-x)}{\partial y}$

-   $x^2+2xy$

------------------------------------------------------------------------

**Practice**

Take the partial derivative with respect to x and to y of the following functions. What would the notation for each look like?

$$3xy-x$$ $$ln(xy)$$ $$x^3+y^3+x^4y^4$$ $$e^{xy}$$

## Integrals

### Area under a curve

Often we want to find the area under a curve. - Net effect of change - Cumulative density functions (CDFs) - Expected values and utilities

Sometimes this is easy. What's the area under the curve between $x=-1$ and $x=1$ for this function? $$f(x) = 
\begin{cases}
\frac{1}{3} & \text{for } x \in [0, 3] \\
0 & \text{otherwise}
\end{cases}$$

::: {.callout-tip title="\"Hint"}
We can draw this and look at the graph. Remember, $area = \ell*w$.
:::

------------------------------------------------------------------------

Sometimes (usually) finding the area under a curve is harder. But this is basically the question behind integration.

### Integrals as summation

You're familiar with summation notation.\
$$\displaystyle\sum_{i=1}^{n} i$$

But this only works when we have discrete values to add. When we need to add continuously, we have to use something else. Specifically, integrals.

### Definite integrals

Let's say we have a function $$ y = x^2 $$ And we want to find the area under the curve from $x=0$ to $x=1$. To find the area we're interested in here, we can use the definite integral.

Generally speaking, the notation looks like this:\
$$\displaystyle\int_{x=a}^{b} f(x),dx$$

Here $a$ is the lower limit of integration, $b$ is the upper limit of integration, our function $f(x)$ is our integrand, and $x$ is our variable of integration.

------------------------------------------------------------------------

For our question, we're looking for $$\displaystyle\int_{x=0}^{1} f(x) dx$$

Which will give us a real number denoting the area under the curve of our function ($y=x^2$) between $x=0$ and $x=1$.

------------------------------------------------------------------------

If $f$ is continuous on $[a,b]$ or bounded on $[a,b]$ with a finite number of discontinuities, then $f$ is integrable on $[a,b]$.

### Indefinite integrals

The *indefinite* integral, or *anti-derivative*, $F(x)$ is the inverse of the function $f'(x)$. $$F(x)= \displaystyle\int f(x) \text{ } dx$$ This means if you take the derivative of $F(x)$, you wind up back at $f(x)$. $$F' = f \text{ or } \displaystyle\frac{dF(x)}{dx} = f(x)$$

This process is called anti-differentiation, or indefinite integration.

------------------------------------------------------------------------

While the definite integral gives us a real number (the total area under a curve), the indefinite integral gives us a function.

We need the concept of indefinite integrals to help us solve definite integrals.

### Solving definite integrals

$$\displaystyle\int_{a}^{b} f(x) \text{ } dx = F(b)-F(a) = F(x)\bigg|_{a}^{b}$$

### Constants

::: callout-note
$C$ in the following slides is the called the "constant of integration." We need to add it when we define *all* antiderivatives (integrals) of a function because the anti-derivative "undoes" the derivative.

Remember that the derivative of any constant is zero. So if we find an integral $F(x)$ whose derivative is $f(x)$, adding (or subtracting) any constant will give us another integral $F(x)+C$ whose derivative is *also* $f(x)$.
:::

### Rules of integration

$$ \displaystyle\int_{a}^{a}f(x) \text{ }dx = 0$$

$$\displaystyle\int_{a}^{b} f(x) \text{ } dx = -\displaystyle\int_{b}^{a}f(x)dx$$

$$\int a \text{ }dx = ax + C \text { where $a$ is a constant}$$

$$\displaystyle\int af(x)dx = a\displaystyle\int f(x) \text{ }dx \text{ where $a$ is a constant}$$

### More rules

$$\int (f(x) + g(x)) \text{ } dx = \int f(x) dx + \int g(x)dx$$

$$\int x^n dx = \frac{x^{n+1}}{n+1} + C \qquad \forall n \neq -1$$

$$\int x^{-1}dx = \ln |x| + C$$

### Solving the problem

Remember our function $y=x^2$ and our goal of finding the area under the curve from $x=0$ to $x=1$.

-   Find the indefinite integral, $F(x)$
    -   $\displaystyle\int x^2 \text{ } dx$
    -   $\displaystyle\frac{x^3}{3}+C$

------------------------------------------------------------------------

-   Evaluate at our lowest and highest points, $F(0)$ and $F(1)$.
    -   $F(0) = 0$
    -   $F(1) = \displaystyle\frac{1}{3}$
    -   Technically $0 + C$ and $\displaystyle\frac{1}{3} + C$, but the C's will fall out in the next step
-   Calculate $F(1) - F(0)$
    -   $\displaystyle\frac{1}{3} - 0 = \displaystyle\frac{1}{3}$

------------------------------------------------------------------------

**Practice --- indefinite integrals**

$$\int x^2 \text{ } dx$$ $$\int 3x^2\text{ } dx$$ $$\int x\text{ } dx$$ $$\int 3x^2 + 2x - 7\text{ }dx$$ $$\int \dfrac{2}{x}\text{ }dx$$

------------------------------------------------------------------------

**Practice --- definite integrals**

$$\displaystyle\int_{1}^{7} x^2 \text{ } dx$$ $$\displaystyle\int_{1}^{10} 3x^2 \text{ } dx$$ $$\int_7^7 x\text{ } dx$$ $$\displaystyle\int_{1}^{5} 3x^2 + 2x - 7\text{ }dx$$ $$\int_{1}^{e} \dfrac{2}{x}\text{ }dx$$

### Integration by parts

-   What if we want to integrate the product of two functions? How to evaluate $\displaystyle\int [f(x)g(x)]dx$?
-   There's a formula for that: integration by parts.
-   We can derive the formula from the product rule for derivatives, which you already know.

------------------------------------------------------------------------

$$\dfrac{d(f(x)g(x))}{d(x)} = f^{'}(x)g(x) + g^{'}(x)f(x)$$

$$\displaystyle\int \dfrac{d(f(x)g(x))}{d(x)} dx= \displaystyle\int [f^{'}(x)g(x) + g^{'}(x)f(x)]dx$$

$$f(x)g(x) = \displaystyle\int f^{'}(x)g(x)dx + \displaystyle\int g^{'}(x)f(x)dx$$

------------------------------------------------------------------------

-   Note that we can't just plug in our two original functions into this formula. We have some work to do first.

-   Board example: $$\int x \sqrt{x}dx$$
