project:
  type: book
  output-dir: _book

book:
  title: "Methods Camp 2023"
  subtitle: "(work in progress)" 
  author: "Andrés Cruz and Matt Martin"
  date: today
  chapters:
    - index.qmd
    - topic1.qmd
    - topic2.qmd
    - topic3.qmd
    - topic4.qmd
    - topic5.qmd
    - topic6.qmd
    - references.qmd
  downloads: pdf
  site-url: https://methodscamp.github.io/

bibliography: references.bib

format:
  html:
    theme: 
        light: flatly
        dark: darkly
  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: auto
