project:
  type: book
  output-dir: _book

book:
  title: "Methods Camp"
  subtitle: "August 2023" 
  author: "Andrés Cruz"
  author: "Matt Martin"
  chapters:
    - index.qmd
    - topic1.qmd
    - topic2.qmd
    - topic3.qmd
    - topic4.qmd
    - topic5.qmd
    - topic6.qmd
    - references.qmd
  downloads: pdf
  site-url: https://methodscamp.github.io/

bibliography: references.bib

format:
  html:
    theme: 
        light: flatly
        dark: darkly
  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: auto
