project:
  type: book
  output-dir: _book

book:
  title: "Methods Camp"
  subtitle: "UT Austin, Department of Government" 
  author: "Andrés Cruz and Matt Martin"
  date: "08/10/2023"
  chapters:
    - index.qmd
    - 00_setup.qmd
    - 01_r_intro.qmd
    - 02_tidy_data1.qmd
    - 03_matrices.qmd
    - 04_tidy_data2.qmd
    - 05_functions.qmd
    - 06_calculus.qmd
    - 07_probability.qmd
    - 08_simulations.qmd
    - 09_textanalysis.qmd
    - 10_wrapup.qmd
    - references.qmd
  downloads: pdf
  site-url: https://methodscamp.github.io/
  repo-url: https://github.com/methodscamp/methodscamp.github.io
  search: true

bibliography: references.bib

nocite: |
  @usda2019, @fivethirtyeight2021, @qog, @smith2020, @wdi, @countrycode, @fuzzyjoin
format:
  html:
    theme: 
        light: flatly
        dark: darkly
    email-obfuscation: javascript
  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: auto
