project:
  type: book
  output-dir: _book
  resources:
    - "previous-editions/**"
    - "previous-editions/2023/Methods-Camp.pdf"

book:
  title: "Methods Camp"
  subtitle: "UT Austin, Department of Government" 
  author: 
    - "Andrés Cruz"
    - "Meiying Xu"
  date: "August 2024"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - 00_setup.qmd
    - 01_r_intro.qmd
    - 02_tidy_data1.qmd
    - references.qmd
  # downloads: pdf
  site-url: https://methodscamp.github.io/
  repo-url: https://github.com/methodscamp/methodscamp.github.io
  search: true

bibliography: references.bib

nocite: |
  @usda2019, @fivethirtyeight2021, @qog, @smith2020, @wdi, @countrycode, 
  @fuzzyjoin, @Vdemcodebook2022, @wickham_ggplot2, @imai_quantitative_2022, 
  @rossi1996mathematics, @moore_mathematics_2013, 
  @baydinAutomaticDifferentiationMachine2017, @Wickham2014,
  @pontinOppenheimerGhost2007, @wickham2014advanced, @aronow2019foundations
format:
  html:
    theme: 
        light: flatly
        dark: darkly
    email-obfuscation: javascript
  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: false
