project:
  type: book
  output-dir: _book

book:
  title: "Methods Camp"
  subtitle: "August 2023" 
  author: "Andrés Cruz and Matt Martin"
  chapters:
    - index.qmd
    - R.qmd
    - tidyverse1.qmd
    - matrices.qmd
    - tidyverse2.qmd
    - functions.qmd
    - calculus.qmd
    - probability.qmd
    - simulations.qmd
    - textanalysis.qmd
    - wrapup.qmd
    - references.qmd
  downloads: pdf
  site-url: https://methodscamp.github.io/

bibliography: references.bib

format:
  html:
    theme: 
        light: flatly
        dark: darkly
  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: auto
