::: {.callout-caution title="WIP"}
These are materials for the ongoing version of Methods Camp (2024). Click [here](/previous-editions/2023) to see last year's materials.
:::

## Class schedule {.unnumbered}

| Date          | Time              | Location   |
|---------------|-------------------|------------|
| Fri, Aug. 16  | 9:00 AM - 4:00 PM | [RLP](https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/utm/rlp/) 2.606  |
| Sat, Aug. 17  | No class          | \-         |
| Sun, Aug. 18  | No class          | \-         |
| Mon, Aug. 19  | 9:00 AM - 4:00 PM | [BAT](https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/UTM/BAT/) 5.108  |
| Tue, Aug. 20  | 9:00 AM - 4:00 PM | [RLP](https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/utm/rlp/) 2.606 |
| Wed, Aug. 21  | 9:00 AM - 4:00 PM | [BAT](https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/UTM/BAT/) 5.108 |
| Thu, Aug. 22  | 9:00 AM - 4:00 PM | [RLP](https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/utm/rlp/) 2.606 |

On class days, we will have a lunch break from 12:00-1:00 PM. We'll also take short breaks periodically during the morning and afternoon sessions as needed.

## Description {.unnumbered}

Welcome to Introduction to Methods for Political Science, aka "Methods Camp"! Methods Camp is designed to give everyone a chance to brush up on some skills in preparation for the introductory Statistics and Formal Theory courses. The other goal of Methods Camp is to allow you to get to know your cohort. We hope that matrix algebra and the chain rule will still prove to be good bonding exercises!

As you can see from the above schedule, we'll be meeting on Friday, August 16th as well as from Monday, August 19th through Thursday, August 22nd. Classes at UT begin the start of the following week on Monday, August 26th. Below is a tentative schedule outlining what will be covered in the class, although we may rearrange things if we find we're going too slowly or too quickly through the material.

## Course outline {.unnumbered}

**1 Friday morning: [Intro to R](01_r_intro.html)**

-   Introductions
-   R and RStudio: basics
-   Objects (vectors, matrices, data frames, etc.)
-   Basic functions (`mean()`, `length()`, etc.)
-   Packages: installation and loading (including the tidyverse)

**2 Friday afternoon: [Tidy data analysis I](02_tidy_data1.html)**

-   Tidy data
-   Data wrangling with dplyr
-   Data visualization basics with `ggplot2`

**3 Monday morning: Functions**

-   Definitions
-   Functions in R
-   Common types of functions
-   Logarithms and exponents
-   Composite functions

**4 Monday afternoon: Calculus**

-   Derivatives
-   Optimization
-   Integrals

**5 Tuesday morning: Matrices**

-   Matrices
-   Systems of linear equations
-   Matrix operations (multiplication, transpose, inverse, determinant)
-   Solving systems of linear equations in matrix form (and why that's cool)
-   Introduction to OLS

**6 Tuesday afternoon: Tidy data analysis II**

-   Loading data in different formats (.csv, R, Excel, Stata, SPSS)
-   Recoding values (`if_else()`, `case_when()`)
-   Handling missing values
-   Pivoting data
-   Merging data
-   Plotting extensions (trend graphs, facets, customization)

**7 Wednesday morning: Probability**

-   Probability: basic concepts
-   Random variables, probability distributions, and their properties
-   Common probability distributions

**8 Wednesday afternoon: Statistics and simulations**

-   Statistics: basic concepts
-   Random sampling and loops in R
-   Simulation example: bootstrapping

**9 Thursday morning: Coding with AI**

-   Visualization tools
-   ⁠Statistical testing and simulation
-   ⁠Text analysis examples

**10 Thursday afternoon: Wrap-up**

-   Project management fundamentals
-   Self-study resources and materials
-   Other software (Overleaf, Zotero, etc.)
-   Methods resources at UT

## Contact info {.unnumbered}

If you have any questions during or outside of methods camp, you can contact us via email. Or if you are curious about our research, you can also check out our respective websites and Twitter accounts (or should we say X...):

-   Andrés Cruz: [andres.cruz\@utexas.edu](mailto:andres.cruz@utexas.edu) [\[Website\]](https://arcruz0.github.io/) [\[Twitter\]](https://twitter.com/arcruz0)

-   Meiying Xu: [xu.meiying\@utexas.edu](mailto:xu.meiying@utexas.edu) [\[Website\]]() [\[Twitter\]]()

## Acknowledgements {.unnumbered}

We thank previous Methods Camp instructors for their accumulated experience and materials, which we have based ours upon. UT Gov Prof. Max Goplerud gave us amazing feedback for this iteration of Methods Camp (2024). All errors remain our own (and will hopefully be fixed with your help!).

## Materials from previous editions {.unnumbered}

- [2023](/previous-editions/2023): co-taught by Andrés Cruz and Matt Martin.
