# Matrices

## Introduction

### Scalars

-   One number (12, for example) is referred to as a scalar.

-   This can be thought of as a 1x1 matrix.

### Vectors

-   We can put several scalars together to make a vector.
-   An example is: $$\begin{bmatrix}
        12 \\
        14 \\
        15
        \end{bmatrix}
        = b$$
-   Since this is a column of numbers, we cleverly refer to it as a column vector.
-   Another example is: $$\begin{bmatrix}
    12 & 14 & 15
    \end{bmatrix}
    = d$$
-   This is called a row vector.

## Operators

### Summation

-   Recall the summation operator $\sum$, which lets us perform an operation on a sequence of numbers (often but not always a vector)

$$x = \begin{bmatrix}
12 & 7 & -2 & 0 & 1
\end{bmatrix}$$

-   We can then calculate... $$\sum_{i=1}^3 x_i$$

-   Which is... $$12+7+-2=17$$

### Product

-   Recall the product operator $\prod$, which can also perform operations over a sequence of numbers

$$z = \begin{bmatrix}
5 & -3 & 5 & 1
\end{bmatrix}$$

-   We can then calculate... $$\prod_{i=1}^4 z_i$$

-   Which multiplies out to... $$5*-3*5*1=-75$$

## Matrices

### Basics

-   We can append vectors together to form a matrix:

$$\begin{bmatrix}
12 & 14 & 15 \\
115 & 22 & 127 \\
193 & 29 & 219
\end{bmatrix}
= A$$

-   We always refer to the dimensions of matrices by row then column (R x C).

    -   Find a way to remember that knowledge [permanently].

-   So, $A$ is a $3x3$ matrix.

    -   Note that matrices are usually designated by capital letters, and sometimes **bolded**, too.

### Structure

-   How do we refer to specific elements of the matrix?

-   Matrix $A$ is an $m\timesn$ matrix where $m=n=3$

-   More generally, matrix $B$ is an $m\times n$ matrix where the elements look like this: $$B=
    \begin{bmatrix}
    b_{11} & b_{12} & b_{13} & \ldots & b_{1n} \\
    b_{21} & b_{22} & b_{23} & \ldots & b_{2n} \\
    \vdots & \vdots & \vdots & \ldots & \vdots \\
    b_{m1} & b_{m2} & b_{m3} & \ldots & b_{mn}
    \end{bmatrix}$$

-   Thus $b_{23}$ refers to the second unit down and third across.
