{
  "hash": "116449a6e4ae5943b0bf7e7d1a9fc926",
  "result": {
    "markdown": "# Matrices\n\nMatrices are rectangular collections of numbers. In this module we will introduce them and review some basic operators, to then introduce a sneak peek of why matrices are useful (and cool).\n\n## Introduction\n\n### Scalars\n\nOne number (for example, 12) is referred to as a scalar.\n\n$$\na = 12\n$$\n\n### Vectors\n\nWe can put several scalars together to make a vector. Here is an example:\n\n$$\n\\overrightarrow b = \n\\begin{bmatrix}\n  12 \\\\\n  14 \\\\\n  15\n\\end{bmatrix}\n$$\n\nSince this is a column of numbers, we cleverly refer to it as a *column vector*.\n\nHere is another example of a vector, this time represented as a *row vector*:\n\n$$\n\\overrightarrow c = \\begin{bmatrix}\n  12 & 14 & 15\n\\end{bmatrix}\n$$\n\nColumn vectors are possibly more common and useful, but we sometimes write things down using row vectors to\n\nVectors are fairly easy to construct in R. As we saw before, we can use the `c()` function to combine elements:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(5, 25, -2, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  5 25 -2  1\n```\n:::\n:::\n\n\n\n::: callout-warning\nRemember that the code above does not *create* any objects. To do so, you'd need to use the assignment operator (`<-`):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvector_example <- c(5, 25, -2, 1)\nvector_example\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  5 25 -2  1\n```\n:::\n:::\n\n\n:::\n\nOr we can also create vectors from sequences with the `:` operator or the `seq()` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10:20\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 10 11 12 13 14 15 16 17 18 19 20\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(from = 3, to = 27, by = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  3  6  9 12 15 18 21 24 27\n```\n:::\n:::\n\n\n\n## Operators\n\n### Summation\n\nThe summation operator $\\sum$ (i.e., the uppercase Sigma letter) lets us perform an operation on a sequence of numbers, which is often but not always a vector.\n\n$$\\overrightarrow d = \\begin{bmatrix}\n12 & 7 & -2 & 3 & -1\n\\end{bmatrix}$$\n\nWe can then calculate the sum of the first three elements of the vector, which is expressed as follows: $$\\sum_{i=1}^3 d_i$$\n\nThen we do the following math: $$12+7+(-2)=17$$\n\nIt is also common to use $n$ in the superscript to indicate that we want to sum all elements:\n\n$$\n\\sum_{i=1}^n d_i = 12 + 7 + (-2) + 3 + (-1) = 19\n$$ We can perform these operations using the `sum()` function in R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvector_d <- c(12, 7, -2, 3, -1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(vector_d[1:3])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(vector_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19\n```\n:::\n:::\n\n\n\n### Product\n\nThe product operator $\\prod$ (i.e., the uppercase Pi letter) can also perform operations over a sequence of elements in a vector. Recall our previous vector:\n\n$$\\overrightarrow d = \\begin{bmatrix}\n12 & 7 & -2 & 3 & 1\n\\end{bmatrix}$$\n\nWe might want to calculate the product of all its elements, which is expressed as follows: $$\\prod_{i=1}^n d_i = 12 \\cdot 7 \\cdot (-2) \\cdot 3 \\cdot (-1) = 504$$\n\nIn R, we can compute products using the `prod()` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprod(vector_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 504\n```\n:::\n:::\n\n\n\n::: callout-note\n## Exercise\n\nGet the product of the first three elements of vector $d$. Write the notation by hand and use R to obtain the number.\n:::\n\n## Matrices\n\n### Basics\n\nWe can append vectors together to form a matrix:\n\n$$A = \\begin{bmatrix}\n12 & 14 & 15 \\\\\n115 & 22 & 127 \\\\\n193 & 29 & 219\n\\end{bmatrix}$$\n\nThe number of rows and columns of a matrix constitute the *dimensions* of the matrix. The first number is the number of rows (\"r\") and the second number is the number of columns (\"c\") in the matrix.\n\n::: callout-important\nFind a way to remember \"r x c\" *permanently*. The order of the dimensions never changes.\n:::\n\nMatrix $A$ above, for example, is a $3x3$ matrix. Sometimes we'd refer to it as $A_{3x3}$.\n\n::: callout-tip\nIt is common to use capital letters (sometimes **bold-faced**) to represent matrices. In contrast, vectors are usually represented with either bold lowercase letters or lowercase letters with an arrow on top (e.g., $\\overrightarrow v$).\n:::\n\n#### Constructing matrices in R {.unnumbered}\n\nThere are different ways to create matrices in R. One of the simplest is via `rbind()` or `cbind()`, which paste vectors together (either by **r**ows or by **c**olumns):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create some vectors\nvector1 <- 1:4\nvector2 <- 5:8\nvector3 <- 9:12\nvector4 <- 13:16\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using rbind(), each vector will be a row \nrbind_mat <- rbind(vector1, vector2, vector3, vector4)\nrbind_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        [,1] [,2] [,3] [,4]\nvector1    1    2    3    4\nvector2    5    6    7    8\nvector3    9   10   11   12\nvector4   13   14   15   16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using cbind(), each vector will be a column\ncbind_mat <- cbind(vector1, vector2, vector3, vector4)\ncbind_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     vector1 vector2 vector3 vector4\n[1,]       1       5       9      13\n[2,]       2       6      10      14\n[3,]       3       7      11      15\n[4,]       4       8      12      16\n```\n:::\n:::\n\n\n\nAn alternative is to use to properly named `matrix()` function. The basic syntax is `matrix(data, nrow, ncol, byrow)`:\n\n-   `data` is the input vector which becomes the data elements of the matrix.\n-   `nrow` is the number of rows to be created.\n-   `ncol` is the number of columns to be created.\n-   `byrow` is a logical clue. If `TRUE` then the input vector elements are arranged by row. By default (`FALSE`), elements are arranged by column.\n\nLet's see some examples:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Elements are arranged sequentially by row.\nM <- matrix(c(1:12), nrow = 4, byrow = T)\nM\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    1    2    3\n[2,]    4    5    6\n[3,]    7    8    9\n[4,]   10   11   12\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Elements are arranged sequentially by column (byrow = F by default).\nN <- matrix(c(1:12), nrow = 4)\nN\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    1    5    9\n[2,]    2    6   10\n[3,]    3    7   11\n[4,]    4    8   12\n```\n:::\n:::\n\n\n\n### Structure\n\nHow do we refer to specific elements of the matrix? For example, matrix $A$ is an $m\\times n$ matrix where $m=n=3$. This is sometimes called a *square matrix*.\n\nMore generally, matrix $B$ is an $m\\times n$ matrix where the elements look like this: $$B=\n\\begin{bmatrix}\nb_{11} & b_{12} & b_{13} & \\ldots & b_{1n} \\\\\nb_{21} & b_{22} & b_{23} & \\ldots & b_{2n} \\\\\n\\vdots & \\vdots & \\vdots & \\ldots & \\vdots \\\\\nb_{m1} & b_{m2} & b_{m3} & \\ldots & b_{mn}\n\\end{bmatrix}$$\n\nThus $b_{23}$ refers to the second unit down and third across. More generally, we refer to row indices as $i$ and to column indices as $j$.\n\nIn R, we can access a matrix's elements using square brackets:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# In matrix N, access the element at 1st row and 3rd column.\nN[1,3]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# In matrix N, access the element at 4th row and 2nd column.\nN[4,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8\n```\n:::\n:::\n\n\n\n::: callout-tip\nWhen trying to identify a specific element, the first subscript is the element's row and the second subscript is the element's column (*always* in that order).\n:::\n\n## Matrix operations\n\n### Addition and subtraction\n\n-   Addition and subtraction are straightforward operations.\n\n-   Matrices must have *exactly* the same dimensions for both of these operations.\n\n-   We add or subtract each element with the corresponding element from the other matrix.\n\n-   This is expressed as follows:\n\n$$A \\pm B=C$$\n\n$$c_{ij}=a_{ij} \\pm b_{ij} \\text{ }\\forall i,j$$\n\n$$\\begin{bmatrix}\na_{11} & a_{12} & a_{13}\\\\\na_{21} & a_{22} & a_{23}\\\\\na_{31} & a_{32} & a_{33}\n\\end{bmatrix}\n\\pm\n\\begin{bmatrix}\nb_{11} & b_{12} & b_{13}\\\\\nb_{21} & b_{22} & b_{23}\\\\\nb_{31} & b_{32} & b_{33}\n\\end{bmatrix}$$ $$=$$ $$\\begin{bmatrix}\na_{11}\\pm b_{11} & a_{12}\\pm b_{12} & a_{13}\\pm b_{13}\\\\\na_{21}\\pm b_{21} & a_{22}\\pm b_{22} & a_{23}\\pm b_{23}\\\\\na_{31}\\pm b_{31} & a_{32}\\pm b_{32} & a_{33}\\pm b_{33}\n\\end{bmatrix}$$\n\n#### Addition and subtraction in R {.unnumbered}\n\nWe start by creating two 2x3 matrices:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create two 2x3 matrices.\nmatrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)\nmatrix1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    3   -1    2\n[2,]    9    4    6\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)\nmatrix2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    5    0    3\n[2,]    2    9    4\n```\n:::\n:::\n\n\n\nWe can simply use the `+` and `-` operators for addition and substraction:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix1 + matrix2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    8   -1    5\n[2,]   11   13   10\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix1 - matrix2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]   -2   -1   -1\n[2,]    7   -5    2\n```\n:::\n:::\n\n\n\n::: callout-note\n## Exercise\n\n(Use code for one of these and do the other one by hand!)\n\n1\\) Calculate $A + B$\n\n$$A= \\begin{bmatrix}\n1 & 0 \\\\\n-2 & -1\n\\end{bmatrix}$$\n\n$$B = \\begin{bmatrix}\n5 & 1 \\\\\n2 & -1\n\\end{bmatrix}$$\\\n\n2\\) Calculate $A - B$\n\n$$A= \\begin{bmatrix}\n6 & -2 & 8 & 12 \\\\\n4 & 42 & 8 & -6\n\\end{bmatrix}$$\n\n$$B = \\begin{bmatrix}\n18 & 42 & 3 & 7 \\\\\n0 & -42 & 15 & 4\n\\end{bmatrix}$$\n:::\n\n### Scalar multiplication\n\nScalar multiplication is very intuitive. As we know, a scalar is a single number. We multiply each value in the matrix by the scalar to perform this operation.\n\nFormally, this is expressed as follows: $$A = \n\\begin{bmatrix}\na_{11} & a_{12} & a_{13}\\\\\na_{21} & a_{22} & a_{23}\\\\\na_{31} & a_{32} & a_{33}\n\\end{bmatrix}$$ $$cA = \n\\begin{bmatrix}\nca_{11} & ca_{12} & ca_{13}\\\\\nca_{21} & ca_{22} & ca_{23}\\\\\nca_{31} & ca_{32} & ca_{33}\n\\end{bmatrix}$$\n\nIn R, all we need to do is take an established matrix and multiply it by some scalar:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# matrix1 from our previous example\nmatrix1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    3   -1    2\n[2,]    9    4    6\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix1 * 3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    9   -3    6\n[2,]   27   12   18\n```\n:::\n:::\n\n\n\n::: callout-note\n## Exercise\n\nCalculate $2\\times A$ and $-3 \\times B$. Again, do one by hand and the other one using R.\n\n$$A= \\begin{bmatrix}\n    1 & 4 & 8 \\\\\n    0 & -1 & 3\n    \\end{bmatrix}$$ $$ B = \\begin{bmatrix}\n    -15 & 1 & 5 \\\\\n    2 & -42 & 0 \\\\\n    7 & 1 & 6\n    \\end{bmatrix}$$\n:::\n\n### Matrix multiplication\n\n-   Multiplying matrices is slightly trickier than multiplying scalars.\n\n-   Two matrices must be *conformable* for them to be multiplied together. This means that the number of columns in the first matrix equals the number of rows in the second.\n\n-   When multiplying $A \\times B$, if $A$ is $m \\times n$, $B$ must have $n$ rows.\n\n::: callout-important\nThe conformability requirement *never* changes. Before multiplying anything, check to make sure the matrices are indeed conformable.\n:::\n\n-   The resulting matrix will have the same number of rows as the first matrix and the number of columns in the second. For example, if $A$ is $i \\times k$ and $B$ is $k \\times j$, then $A \\times B$ will be $i \\times j$.\n\n------------------------------------------------------------------------\n\nWhich of the following can we multiply? What will be the dimensions of the resulting matrix? $$\\begin{aligned}\nB=\n\\begin{bmatrix}\n2 \\\\\n3\\\\\n4\\\\\n1\n\\end{bmatrix}\nM = \n\\begin{bmatrix}\n1 & 0 & 2\\\\\n1 & 2 & 4\\\\\n2 & 3 & 2\n\\end{bmatrix}\nL = \n\\begin{bmatrix}\n6 & 5 & -1\\\\\n1 & 4 & 3 \n\\end{bmatrix}\n\\end{aligned}$$\n\nWhy can't we multiply in the opposite order?\n\n::: callout-warning\nWhen multiplying matrices, *order matters*. Even if multiplication is possible in both directions, in general $AB \\neq BA$.\n:::\n\n#### Multiplication steps {.unnumbered}\n\n-   Multiply each row by each column, summing up each pair of multiplied terms.\n\n::: callout-tip\nThis is sometimes to referred to as the \"dot product,\" where we multiply matching members, then sum up.\n:::\n\n-   The element in position $ij$ is the sum of the products of elements in the $i$th row of the first matrix ($A$) and the corresponding elements in the $j$th column of the second matrix ($B$). $$c_{ij}=\\sum_{k=1}^n a_{ik}b_{kj}$$\n\n#### Example {.unnumbered}\n\nSuppose a company manufactures two kinds of furniture: chairs and sofas.\n\n-   A chair costs \\$100 for wood, \\$270 for cloth, and \\$130 for feathers.\n\n-   Each sofa costs \\$150 for wood, \\$420 for cloth, and \\$195 for feathers.\n\n|          | Chair | Sofa |\n|----------|-------|------|\n| Wood     | 100   | 150  |\n| Cloth    | 270   | 420  |\n| Feathers | 130   | 195  |\n\nThe same information about unit cost ($C$) can be presented as a matrix.\n\n$$C = \\begin{bmatrix}\n100 & 150\\\\\n270 & 420\\\\\n130 & 195\n\\end{bmatrix}$$\n\nNote that each of the three rows of this 3 x 2 matrix represents a material (wood, cloth, or feathers), and each of the two columns represents a product (chair or coach). The elements are the unit cost (in USD).\n\n------------------------------------------------------------------------\n\nNow, suppose that the company will produce 45 chairs and 30 sofas this month. This production quantity can be represented in the following table, and also as a 2 x 1 matrix ($Q$):\n\n| Product | Quantity |\n|---------|----------|\n| Chair   | 45       |\n| Sofa    | 30       |\n\n$$Q = \\begin{bmatrix}\n45 \\\\\n30 \n\\end{bmatrix}$$\n\nWhat will be the company's total cost? The \"total expenditure\" is equal to the \"unit cost\" times the \"production quantity\" (the number of units).\n\nThe total expenditure ($E$) for each material this month is calculated by multiplying these two matrices.\n\n$$\\begin{aligned} E = CQ =\n\\begin{bmatrix}\n100 & 150\\\\\n270 & 420\\\\\n130 & 195\n\\end{bmatrix}\n\\begin{bmatrix}\n45 \\\\\n30 \n\\end{bmatrix} =\n\\begin{bmatrix}\n(100)(45) + (150)(30) \\\\\n(270)(45) + (420)(30) \\\\\n(130)(45) + (195)(30)\n\\end{bmatrix} =\n\\begin{bmatrix}\n9,000 \\\\\n24,750 \\\\\n11,700\n\\end{bmatrix}\n\\end{aligned}$$\n\nMultiplying the 3x2 Cost matrix ($C$) times the 2x1 Quantity matrix ($Q$) yields the 3x1 Expenditure matrix ($E$).\n\nAs a result of this matrix multiplication, we determine that this month the company will incur expenditures of:\n\n-   \\$9,000 for wood\n-   \\$24,750 for cloth\n-   \\$11,700 for feathers.\n\n#### Matrix multiplication in R {.unnumbered}\n\nBefore attempting matrix multiplication, we must make sure the matrices are conformable (as we do for our manual calculations).\n\nThen we can multiply our matrices together using the `%*%` operator.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nC <- matrix(c(100, 270, 130, 150, 420, 195), nrow = 3)\nC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2]\n[1,]  100  150\n[2,]  270  420\n[3,]  130  195\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nQ <- matrix(c(45, 30), nrow = 2)\nQ\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1]\n[1,]   45\n[2,]   30\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nC %*% Q\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      [,1]\n[1,]  9000\n[2,] 24750\n[3,] 11700\n```\n:::\n:::\n\n\n\n::: callout-warning\nIf you have a missing value or `NA` in one of the matrices you are trying to multiply (something we will discuss in further detail in the next module), you will have `NA`s in your resulting matrix.\n:::\n\n```         \n```\n\n### Properties of operations\n\n-   Addition and subtraction:\n\n    -   Associative: $(A \\pm B) \\pm C = A \\pm (B \\pm C)$\n\n    -   Communicative: $A \\pm B = B \\pm A$\n\n-   Multiplication:\n\n    -   $AB \\neq BA$\n\n    -   $A(BC) = (AB)C$\n\n    -   $A(B+C) = AB + AC$\n\n    -   $(A+B)C = AC + BC$\n\n## Special matrices\n\n**Square matrix**\n\n-   In a square matrix, the number of rows equals the number of columns ($m=n$):\n\n-   The *diagonal* of a matrix is a set of numbers consisting of the elements on the line from the upper-left-hand to the lower-right-hand corner of the matrix. Diagonals are particularly useful in square matrices.\n\n-   The *trace* of a matrix, denoted as $tr(A)$, is the sum of the diagonal elements of the matrix.\n\n**Diagonal matrix:**\n\n-   In a diagonal matrix, all of the elements of the matrix that are not on the diagonal are equal to zero.\n\n**Scalar matrix:**\n\n-   A scalar matrix is a diagonal matrix where the diagonal elements are all equal to each other. In other words, we're really only concerned with one scalar (or element) held in the diagonal.\n\n**Identity matrix:**\n\n-   The identity matrix is a scalar matrix with all of the diagonal elements equal to one.\n\n-   Remember that, as with all diagonal matrices, the off-diagonal elements are equal to zero.\n\n-   The capital letter $I$ is reserved for the identity matrix. For convenience, a 3x3 identity matrix can be denoted as $I_3$.\n\n## Transpose\n\nThe transpose is the original matrix with the rows and the columns interchanged.\n\nThe notation is either $J'$ (\"J prime\") or $J^T$ (\"J transpose\").\n\n$$J =\n\\begin{bmatrix}\n4 & 5\\\\\n3 & 0\\\\\n7 & -2\n\\end{bmatrix}$$\n\n$$J' = J^T = \n\\begin{bmatrix}\n4 & 3 & 7 \\\\\n5 & 0 & -2\n\\end{bmatrix}$$\n\nIn R, we use `t()` to get the transpose.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nJ <- matrix(c(4, 3, 7, 5, 0, -2), ncol = 2)\nJ\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2]\n[1,]    4    5\n[2,]    3    0\n[3,]    7   -2\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt(J)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    4    3    7\n[2,]    5    0   -2\n```\n:::\n:::\n\n\n\n## Inverse\n\n-   Just like a number has a reciprocal, a matrix has an inverse.\n\n-   When we multiply a matrix by its inverse we get the identity matrix (which is like \"1\" for matrices).\n\n$$A × A^{-1} = I$$\n\n-   The inverse of A is $A^{-1}$ only when:\n\n$$AA^{-1} = A^{-1}A = I$$\n\n-   Sometimes there is no inverse at all.\n\n::: callout-note\nFor now, don't worry about calculating the inverse of a matrix manually. This is the type of task we use R for.\n:::\n\n-   In R, we use the `solve()` function to calculate the inverse of a matrix:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- matrix(c(3, 2, 5, 2, 3, 2, 5, 2, 4), ncol = 3)\nA\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3]\n[1,]    3    2    5\n[2,]    2    3    2\n[3,]    5    2    4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsolve(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            [,1]        [,2]       [,3]\n[1,] -0.29629630 -0.07407407  0.4074074\n[2,] -0.07407407  0.48148148 -0.1481481\n[3,]  0.40740741 -0.14814815 -0.1851852\n```\n:::\n:::\n\n\n\n## Linear systems and matrices\n\n-   A system of equations can be represented by an *augmented matrix*.\n\n-   System of equations: $${\\color{red}{3}}x + {\\color{green}{6}}y = {\\color{blue}{12}}$$ $${\\color{red}{5}}x + {\\color{green}{10}}y = {\\color{blue}{25}}$$\n\n-   In an augmented matrix, each row represents one equation in the system and each column represents a variable or the constant terms. $$\\begin{bmatrix}\n    {\\color{red}{3}} & {\\color{green}{6}} & {\\color{blue}{12}}\\\\\n    {\\color{red}{5}} & {\\color{green}{10}} & {\\color{blue}{25}}\n    \\end{bmatrix}$$\n\n## OLS and matrices\n\n-   We can use the logic above to calculate estimates for our ordinary least squares (OLS) models.\n\n-   OLS is a linear regression technique used to find the best-fitting line for a set of data points (observations) by minimizing the residuals (the differences between the observed and predicted values).\n\n-   We minimize the *sum of the squared errors*.\n\n### Dependent variable\n\n-   Suppose, for example, we have a sample consisting of $n$ observations.\n\n-   The dependent variable is denoted as an $n \\times1$ column vector.\n\n$$Y = \\begin{bmatrix}\ny_1 \\\\\ny_2 \\\\\ny_3 \\\\\n\\vdots \\\\\ny_n\n\\end{bmatrix}$$\n\n### Independent variables\n\n-   Suppose there are $k$ independent variables and a constant term, meaning $k+1$ columns and $n$ rows.\n\n-   We can represent these variables as an $n \\times (k+1)$ matrix, expressed as follows:\n\n$$X= \\begin{bmatrix}\n1 & x_{11} & \\dots & x_{1k} \\\\\n1 & x_{21} & \\dots & x_{2k} \\\\\n\\vdots & \\vdots & \\dots & \\vdots \\\\\n1 & x_{n1} & \\dots & x_{nk}\n\\end{bmatrix}$$\n\n-   $x_{ij}$ is the $i$-th observation of the $j$-th independent variable.\n\n### Linear regression model\n\n-   Let's say we have 173 observations (n = 173) and 2 IVs (k = 3).\n\n-   This can be expressed as the following linear equation: $$y = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\epsilon$$\n\n-   In matrix form, we have: $$\\begin{aligned} \\begin{bmatrix}\n    y_1 \\\\\n    y_2 \\\\\n    \\vdots \\\\\n    y_n\n    \\end{bmatrix} = \\begin{bmatrix}\n    1 & x_{11} & x_{21} \\\\\n    1 & x_{21} & x_{22} \\\\\n    \\vdots & \\vdots & \\vdots \\\\\n    1 & x_{1173} & x_{2173} \n    \\end{bmatrix} \\begin{bmatrix}\n    \\beta_0 \\\\\n    \\beta_1 \\\\\n    \\beta_2 \n    \\end{bmatrix} + \\begin{bmatrix}\n    \\epsilon_1 \\\\\n    \\epsilon_2 \\\\\n    \\vdots \\\\\n    \\epsilon_{173}\n    \\end{bmatrix}\\end{aligned} $$\n\n-   All 173 equations can be represented by: $$y=X\\beta+\\epsilon$$\n\n### Estimates\n\n-   Without getting too much into the mechanics, we can calculate our coefficient estimates with matrix algebra using the following equation:\n\n$$\\hat{\\beta} = (X'X)^{-1}X'Y$$\n\n-   Read aloud, we say \"X prime X inverse, X prime Y\".\n\n-   The little hat on our beta ($\\hat{\\beta}$) signifies that these are estimates, that is our OLS estimators.\n\n-   Remember, the OLS method is to choose $\\hat{\\beta}$ such that the sum of squared residuals (\"SSR\") is minimized.\n\n#### Example in R\n\n-   We will load the `mtcars` data set (our favorite) for this example, which contains data about many different car models.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncars_df <- mtcars\n```\n:::\n\n\n\n-   Now, we want to estimate the association between `hp` (horsepower) and `wt` (weight), our independent variables, and `mpg` (miles per gallon), our dependent variable.\n\n-   First, we transform our dependent variable into a matrix, using the `as.matrix` function and specifying the column of the `mtcars` data set to create a column vector of our observed values for the DV.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY <- as.matrix(cars_df[,1])\nY\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      [,1]\n [1,] 21.0\n [2,] 21.0\n [3,] 22.8\n [4,] 21.4\n [5,] 18.7\n [6,] 18.1\n [7,] 14.3\n [8,] 24.4\n [9,] 22.8\n[10,] 19.2\n[11,] 17.8\n[12,] 16.4\n[13,] 17.3\n[14,] 15.2\n[15,] 10.4\n[16,] 10.4\n[17,] 14.7\n[18,] 32.4\n[19,] 30.4\n[20,] 33.9\n[21,] 21.5\n[22,] 15.5\n[23,] 15.2\n[24,] 13.3\n[25,] 19.2\n[26,] 27.3\n[27,] 26.0\n[28,] 30.4\n[29,] 15.8\n[30,] 19.7\n[31,] 15.0\n[32,] 21.4\n```\n:::\n:::\n\n\n\n-   Next, we do the same thing for our independent variables of interest, and our constant.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create two separate matrices for IVs\nX1 <- as.matrix(cars_df[,4])\nX2 <- as.matrix(cars_df[,6])\n\n# create constant column\n\n# bind them altogether into one matrix\nconstant <-  rep(1,nrow(X1))\nX <- cbind(constant,X1,X2)\nX\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      constant          \n [1,]        1 110 2.620\n [2,]        1 110 2.875\n [3,]        1  93 2.320\n [4,]        1 110 3.215\n [5,]        1 175 3.440\n [6,]        1 105 3.460\n [7,]        1 245 3.570\n [8,]        1  62 3.190\n [9,]        1  95 3.150\n[10,]        1 123 3.440\n[11,]        1 123 3.440\n[12,]        1 180 4.070\n[13,]        1 180 3.730\n[14,]        1 180 3.780\n[15,]        1 205 5.250\n[16,]        1 215 5.424\n[17,]        1 230 5.345\n[18,]        1  66 2.200\n[19,]        1  52 1.615\n[20,]        1  65 1.835\n[21,]        1  97 2.465\n[22,]        1 150 3.520\n[23,]        1 150 3.435\n[24,]        1 245 3.840\n[25,]        1 175 3.845\n[26,]        1  66 1.935\n[27,]        1  91 2.140\n[28,]        1 113 1.513\n[29,]        1 264 3.170\n[30,]        1 175 2.770\n[31,]        1 335 3.570\n[32,]        1 109 2.780\n```\n:::\n:::\n\n\n\n-   Next, we calculate $X'X$, $X'Y$, and $(X'X)^{-1}$.\n\n::: callout-reminder\nDon't forget to use `%*%` for matrix multiplication!\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# X prime X\nXpX <- t(X)%*%X\n\n# X prime X inverse\nXpXinv <- solve(XpX)\n\n# X prime Y\nXpY <- t(X)%*%Y\n\n# beta coefficient estimates\nbhat <- XpXinv %*% XpY\nbhat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                [,1]\nconstant 37.22727012\n         -0.03177295\n         -3.87783074\n```\n:::\n:::\n",
    "supporting": [
      "03_matrices_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}